test inifinite recursion in partitionWeighted()
This happens when there are 2 elements with the same weight. That is
rare, so it was hard to spot.

    Error: call depth limit reached